#ifndef INDEXES_H
#define INDEXES_H

#define ID_R 2
#define ID_L 1
#define ID_FL 1
#define ID_FR 1
#define ID_BR 2
#define ID_BL 2

//new
#define INDEX_FL_POS_P 12
#define INDEX_FR_POS_P 0
#define INDEX_BL_POS_P 0
#define INDEX_BR_POS_P 12
#define INDEX_FL_POS_I 13
#define INDEX_FR_POS_I 1
#define INDEX_BL_POS_I 1
#define INDEX_BR_POS_I 13
#define INDEX_FL_POS_D 14
#define INDEX_FR_POS_D 2
#define INDEX_BL_POS_D 2
#define INDEX_BR_POS_D 14
#define INDEX_FL_POS_ERROR_LIMIT 15
#define INDEX_FR_POS_ERROR_LIMIT 3
#define INDEX_BL_POS_ERROR_LIMIT 3
#define INDEX_BR_POS_ERROR_LIMIT 15
#define INDEX_FL_POS_OUT_LIMIT 16
#define INDEX_FR_POS_OUT_LIMIT 4
#define INDEX_BL_POS_OUT_LIMIT 4
#define INDEX_BR_POS_OUT_LIMIT 16
#define INDEX_FL_TARGET_ANG 17
#define INDEX_FR_TARGET_ANG 5
#define INDEX_BL_TARGET_ANG 5
#define INDEX_BR_TARGET_ANG 17
#define INDEX_FL_SPD_P 18
#define INDEX_FR_SPD_P 6
#define INDEX_BL_SPD_P 6
#define INDEX_BR_SPD_P 18
#define INDEX_FL_SPD_I 19
#define INDEX_FR_SPD_I 7
#define INDEX_BL_SPD_I 7
#define INDEX_BR_SPD_I 19
#define INDEX_FL_SPD_D 20
#define INDEX_FR_SPD_D 8
#define INDEX_BL_SPD_D 8
#define INDEX_BR_SPD_D 20
#define INDEX_FL_SPD_ERROR_LIMIT 21
#define INDEX_FR_SPD_ERROR_LIMIT 9
#define INDEX_BL_SPD_ERROR_LIMIT 9
#define INDEX_BR_SPD_ERROR_LIMIT 21
#define INDEX_FL_SPD_OUT_LIMIT 22
#define INDEX_FR_SPD_OUT_LIMIT 10
#define INDEX_BL_SPD_OUT_LIMIT 10
#define INDEX_BR_SPD_OUT_LIMIT 22
#define INDEX_FL_ACTUAL_ANG 23
#define INDEX_FR_ACTUAL_ANG 11
#define INDEX_BL_ACTUAL_ANG 11
#define INDEX_BR_ACTUAL_ANG 23
#define INDEX_L_TARGET_DIR 24
#define INDEX_R_TARGET_DIR 24
#define INDEX_L_TARGET_RPM 25
#define INDEX_R_TARGET_RPM 25
#define INDEX_L_P 26
#define INDEX_R_P 26
#define INDEX_L_I 27
#define INDEX_R_I 27
#define INDEX_L_D 28
#define INDEX_R_D 28
#define INDEX_L_ERROR_LIMIT 29
#define INDEX_R_ERROR_LIMIT 29
#define INDEX_L_OUTPUT_LIMIT 30
#define INDEX_R_OUTPUT_LIMIT 30
#define INDEX_L_ACTUAL_RPM 31
#define INDEX_R_ACTUAL_RPM 31
#define INDEX_L_ACTUAL_DIR 32
#define INDEX_R_ACTUAL_DIR 32


#endif

